import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { ScrollArea } from '@/components/ui/scroll-area';
import { Separator } from '@/components/ui/separator';
import { History, Download, FileText, Clock, Trash2, User } from 'lucide-react';
import { DrawHistoryEntry, Category, TicketOwner } from '@/types/raffle';
import { cn } from '@/lib/utils';
import { format, parse } from 'date-fns';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { useEffect, useState } from 'react';
import { drawResults } from '@/service/employeeApi';

interface DrawHistoryProps {
  history: DrawHistoryEntry[];
  onReset: () => void;
  getOwnerByTicket: (ticketNumber: string) => TicketOwner | undefined;
}

const categoryColors: Record<Category, string> = {
  A: 'bg-category-a text-category-a-foreground',
  B: 'bg-category-b text-category-b-foreground',
  C: 'bg-category-c text-category-c-foreground',
};

const getCategoryColor = (category: string) => {
  if (categoryColors[category]) {
    return categoryColors[category];
  }
  const hue = (category.charCodeAt(0) * 137) % 360;
  return `bg-[hsl(${hue},70%,50%)] text-white`;
};

export function DrawHistory({
  history,
  onReset,
  getOwnerByTicket,
  refetchResults,
}: DrawHistoryProps) {
  const [drawResult, setDrawResult] = useState([]);
  const exportToCSV = () => {
    const source = drawResult.length ? drawResult : history;
    if (!source || source.length === 0) return;

    const rows = [['Ticket Number', 'Prize', 'Category', 'Draw Date & Time']];

    source.forEach((entry: any) => {
      const created = entry.created_at || entry.timestamp || entry.createdAt;
      const parsed = created ? new Date(created.replace(' ', 'T') + 'Z') : new Date();
      rows.push([
        entry.ticket_number || entry.ticketNumber || entry.ticket,
        entry.prize || (entry.prize && entry.prize.name) || '-',
        entry.category || '-',
        // entry.draw_size || entry.drawSize || '-',
        format(parsed, 'dd MMM yyyy, h:mm a'),
      ]);
    });

    const csvContent = rows.map((row) => row.map((cell) => `"${cell}"`).join(',')).join('\n');
    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `raffle-results-${format(new Date(), 'yyyy-MM-dd-HHmmss')}.csv`;
    link.click();
    URL.revokeObjectURL(url);
  };

  const exportToPDF = () => {
    const source = drawResult.length ? drawResult : history;
    if (!source || source.length === 0) return;

    const doc = new jsPDF('p', 'pt');
    const marginLeft = 40;
    const startY = 70;

    doc.setFontSize(18);
    doc.text('Raffle Draw Results', marginLeft, 40);

    // Optional date range
    const dates = source
      .map((e: any) =>
        e.created_at ? parse(e.created_at, 'yyyy-MM-dd HH:mm:ss', new Date()) : new Date()
      )
      .sort((a: Date, b: Date) => +a - +b);
    if (dates.length) {
      const rangeText = `${format(dates[0], 'dd MMM yyyy')} - ${format(
        dates[dates.length - 1],
        'dd MMM yyyy'
      )}`;
      doc.setFontSize(10);
      doc.setTextColor(100);
      // doc.text(`Date Range: ${rangeText}`, marginLeft, 54);
      doc.text(`Generated: ${format(new Date(), 'dd MMM yyyy, h:mm a')}`, marginLeft, 66);
    }

    const tableData = source.map((entry: any) => {
      const created = entry.created_at || entry.timestamp || entry.createdAt;
      const parsed = created ? new Date(created.replace(' ', 'T') + 'Z') : new Date();
      return [
        entry.ticket_number || entry.ticketNumber || entry.ticket,
        entry.prize || (entry.prize && entry.prize.name) || '-',
        entry.category || '-',
        // entry.draw_size || entry.drawSize || '-',
        format(parsed, 'dd MMM yyyy, h:mm a'),
      ];
    });

    autoTable(doc, {
      head: [['Ticket Number', 'Prize', 'Category', 'Draw Date & Time']],
      body: tableData,
      startY,
      styles: { fontSize: 10 },
      headStyles: { fillColor: [59, 130, 246] },
      alternateRowStyles: { fillColor: [245, 247, 250] },
      margin: { left: marginLeft, right: marginLeft },
      didDrawPage: (data) => {
        // footer handled after table generation
      },
    });

    // Add page numbers / footer
    const pageCount = doc.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(9);
      doc.setTextColor(120);
      const pageStr = `Page ${i} of ${pageCount}`;
      doc.text(
        pageStr,
        doc.internal.pageSize.getWidth() - marginLeft,
        doc.internal.pageSize.getHeight() - 30,
        { align: 'right' }
      );
      doc.text('Generated by Raffle System', marginLeft, doc.internal.pageSize.getHeight() - 30);
    }

    doc.save(`raffle-results-${format(new Date(), 'yyyy-MM-dd-HHmmss')}.pdf`);
  };

  const totalWinners = history.reduce((acc, entry) => acc + entry.results.length, 0);

  const getDrawResults = async () => {
    try {
      const res = await drawResults();
      setDrawResult(res.data);
    } catch (error) {
      console.error('Error fetching tickets:', error);
    }
  };

  useEffect(() => {
    getDrawResults();
  }, [refetchResults]);

  console.log('drawResult:', drawResult);
  return (
    <Card className="h-full">
      <CardHeader className="pb-3">
        <div className="flex items-center w-full gap-4">
          <CardTitle className="flex items-center gap-2 text-lg">
            <History className="h-5 w-5 text-primary" />
            Draw History
          </CardTitle>

          <div className="ml-auto flex items-center gap-2">
            <Badge variant="secondary" className="inline-flex">
              {drawResult.length || 0} winners
            </Badge>
            <Button
              variant="outline"
              size="sm"
              onClick={exportToPDF}
              disabled={drawResult.length === 0 && history.length === 0}
            >
              <FileText className="h-4 w-4 mr-1" />
              PDF
            </Button>
            <Button
              variant="outline"
              size="sm"
              onClick={exportToCSV}
              disabled={drawResult.length === 0 && history.length === 0}
            >
              <Download className="h-4 w-4 mr-1" />
              CSV
            </Button>
          </div>
        </div>
      </CardHeader>

      <CardContent className="space-y-4">
        <ScrollArea className="h-[400px]">
          {drawResult.length === 0 ? (
            <div className="flex flex-col items-center justify-center h-full text-muted-foreground py-12">
              <History className="h-12 w-12 mb-3 opacity-30" />
              <p className="text-sm">No draws yet</p>
              <p className="text-xs text-muted-foreground/70">Results will appear here</p>
            </div>
          ) : (
            <div className="overflow-auto">
              <table className="min-w-full divide-y divide-muted rounded-lg bg-card">
                <thead className="bg-muted/50">
                  <tr className="sr-only">
                    <th>Ticket Number</th>
                    <th>Prize</th>
                    <th>Category</th>
                    {/* <th>Draw Size</th> */}
                    <th>Draw Date & Time</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-muted/30">
                  {drawResult.map((entry: any, idx: number) => {
                    const created = entry.created_at || entry.timestamp || entry.createdAt;
                    const parsed = created ? new Date(created.replace(' ', 'T') + 'Z') : new Date();
                    return (
                      <tr key={`${entry.ticket_number}-${idx}`} className="bg-card">
                        <td className="px-4 py-3 align-middle font-mono font-bold">
                          #{entry.ticket_number}
                        </td>
                        <td className="px-4 py-3 align-middle text-sm">{entry.prize}</td>
                        <td className="px-4 py-3 align-middle">
                          <span
                            className={cn(
                              'inline-flex items-center px-2 py-1 rounded-md text-xs font-medium',
                              getCategoryColor(entry.category)
                            )}
                          >
                            {entry.category}
                          </span>
                        </td>
                        {/* <td className="px-4 py-3 align-middle text-sm">{entry.draw_size}</td> */}
                        <td className="px-4 py-3 align-middle text-sm text-muted-foreground">
                          {format(parsed, 'dd MMM yyyy, h:mm a')}
                        </td>
                      </tr>
                    );
                  })}
                </tbody>
              </table>
            </div>
          )}
        </ScrollArea>
      </CardContent>
    </Card>
  );
}
